version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'Dependabot'

  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'Dependabot'

  - package-ecosystem: 'nuget'
    directory: “/”
    target-branch: 'develop'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'Dependabot'
